# Generated by Django 2.2.12 on 2024-06-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='laptop_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
