# Generated by Django 2.2.12 on 2024-06-18 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('office', '0001_initial'),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('hr', 'hr'), ('employee', 'employee'), ('employer', 'employer')], default='employee', max_length=200)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.Department')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.Device')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office.Office')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
